#!/bin/bash
set -e

# Xorg Workspace Kiosk Installer
# Interactive installer for multi-workspace kiosk automation

echo "=========================================="
echo "  Xorg Workspace Kiosk - Installer"
echo "=========================================="
echo ""

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/workspaces.conf"

# Ensure running on Ubuntu/Debian-based system
if ! command -v apt-get &> /dev/null; then
    echo "Warning: This installer uses apt-get. Continue anyway? (y/n)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Installation aborted."
        exit 1
    fi
fi

# Ensure not running as root
if [[ $EUID -eq 0 ]]; then
   echo "ERROR: Do not run this script as root/sudo."
   echo "Run as your regular user: ./install.sh"
   exit 1
fi

# Interactive configuration generator
generate_config() {
    echo ""
    echo "=========================================="
    echo "  Workspace Configuration Setup"
    echo "=========================================="
    echo ""
    echo "Let's configure your workspaces..."
    echo ""
    
    # Ask for number of workspaces
    while true; do
        read -p "How many workspaces do you want to configure? (1-10): " workspace_count
        if [[ "$workspace_count" =~ ^[1-9]$|^10$ ]]; then
            break
        else
            echo "Please enter a number between 1 and 10"
        fi
    done
    
    # Start building config file
    cat > "$CONFIG_FILE" << 'EOF'
# Workspace Configuration File
# Auto-generated by interactive installer

EOF
    
    # Configure each workspace
    for ((i=0; i<workspace_count; i++)); do
        echo ""
        echo "--- Workspace $i ---"
        echo "What would you like to launch here?"
        echo "  1) Chromium (webpage)"
        echo "  2) Firefox (webpage)"
        echo "  3) Custom application"
        
        while true; do
            read -p "Choice (1-3): " choice
            case $choice in
                1)
                    type="chromium"
                    read -p "Enter URL (include https://): " url
                    read -p "Friendly name (optional): " name
                    
                    echo "" >> "$CONFIG_FILE"
                    echo "[workspace-$i]" >> "$CONFIG_FILE"
                    echo "type = $type" >> "$CONFIG_FILE"
                    echo "url = $url" >> "$CONFIG_FILE"
                    if [ -n "$name" ]; then
                        echo "name = $name" >> "$CONFIG_FILE"
                    fi
                    break
                    ;;
                2)
                    type="firefox"
                    read -p "Enter URL (include https://): " url
                    read -p "Friendly name (optional): " name
                    
                    echo "" >> "$CONFIG_FILE"
                    echo "[workspace-$i]" >> "$CONFIG_FILE"
                    echo "type = $type" >> "$CONFIG_FILE"
                    echo "url = $url" >> "$CONFIG_FILE"
                    if [ -n "$name" ]; then
                        echo "name = $name" >> "$CONFIG_FILE"
                    fi
                    break
                    ;;
                3)
                    type="app"
                    read -p "Enter full command/path to application: " command
                    read -p "Friendly name (optional): " name
                    
                    echo "" >> "$CONFIG_FILE"
                    echo "[workspace-$i]" >> "$CONFIG_FILE"
                    echo "type = $type" >> "$CONFIG_FILE"
                    echo "command = $command" >> "$CONFIG_FILE"
                    if [ -n "$name" ]; then
                        echo "name = $name" >> "$CONFIG_FILE"
                    fi
                    break
                    ;;
                *)
                    echo "Invalid choice. Please enter 1, 2, or 3"
                    ;;
            esac
        done
    done
    
    echo ""
    echo "Configuration saved to: $CONFIG_FILE"
    echo "You can edit this file later to make changes."
}

# Check if config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo "No configuration file found."
    echo ""
    read -p "Would you like to create one interactively? (y/n): " response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        generate_config
    else
        echo ""
        echo "Please create a workspaces.conf file manually."
        echo "See workspaces.conf.example for format."
        exit 1
    fi
else
    echo "✓ Found existing configuration: $CONFIG_FILE"
fi

echo ""
echo "=========================================="
echo "  Beginning Installation"
echo "=========================================="
echo ""

echo "[1/8] Checking display server..."
if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
    echo "WARNING: You are running Wayland. This setup requires Xorg for reliable automation."
    echo "To switch to Xorg:"
    echo "  1. Log out"
    echo "  2. At login screen, click the gear icon"
    echo "  3. Select 'Ubuntu on Xorg'"
    echo "  4. Log back in and re-run this installer"
    echo ""
    echo "Continue anyway? (not recommended) (y/n)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Installation aborted. Please switch to Xorg and try again."
        exit 1
    fi
fi

echo "[2/8] Installing dependencies..."
sudo apt-get update
sudo apt-get install -y \
    wmctrl \
    xdotool \
    chromium-browser \
    x11-xserver-utils \
    cron

echo "[3/8] Creating directory structure..."
mkdir -p "$HOME/.config/systemd/user"
mkdir -p "$HOME/.config/autostart"
mkdir -p "$HOME/bin"

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "[4/8] Copying configuration file..."
cp "$CONFIG_FILE" "$HOME/.config/workspaces.conf"

echo "[5/8] Installing workspace launcher script..."
cp "$SCRIPT_DIR/workspace-launcher.sh" "$HOME/bin/workspace-launcher.sh"
chmod +x "$HOME/bin/workspace-launcher.sh"

echo "[6/8] Installing health check script..."
cp "$SCRIPT_DIR/kiosk-health-check.sh" "$HOME/bin/kiosk-health-check.sh"
chmod +x "$HOME/bin/kiosk-health-check.sh"

echo "[7/8] Installing systemd service..."
cp "$SCRIPT_DIR/systemd/workspace-automation.service" "$HOME/.config/systemd/user/"
systemctl --user daemon-reload
systemctl --user enable workspace-automation.service

echo "[8/8] Configuring session preferences..."
# Create/update xinitrc for screen blanking settings
if [ ! -f "$HOME/.xinitrc" ]; then
    cat > "$HOME/.xinitrc" << 'EOF'
#!/bin/bash
# Disable screen blanking and power management for kiosk mode
xset s off
xset -dpms
xset s noblank
EOF
    chmod +x "$HOME/.xinitrc"
else
    echo "Note: ~/.xinitrc already exists. Add these lines manually if needed:"
    echo "  xset s off"
    echo "  xset -dpms"
    echo "  xset s noblank"
fi

# Setup health check cron job
echo "Setting up health monitoring (requires sudo for cron)..."
CRON_JOB="*/5 * * * * DISPLAY=:0 $HOME/bin/kiosk-health-check.sh >> $HOME/kiosk-health.log 2>&1"
(crontab -l 2>/dev/null | grep -v "kiosk-health-check.sh"; echo "$CRON_JOB") | crontab -

echo ""
echo "=================================="
echo "Installation Complete!"
echo "=================================="
echo ""
echo "IMPORTANT: To apply screen blanking settings, run these commands now:"
echo "  xset s off"
echo "  xset -dpms"
echo "  xset s noblank"
echo ""
echo "To start the workspace automation:"
echo "  systemctl --user start workspace-automation.service"
echo ""
echo "To check status:"
echo "  systemctl --user status workspace-automation.service"
echo ""
echo "To view logs:"
echo "  journalctl --user -u workspace-automation.service -f"
echo ""
echo "The service will auto-start on next login."
echo ""
echo "Health monitoring will check windows every 5 minutes."
echo "Check logs: tail -f ~/kiosk-health.log"
echo ""
